import type { Spot } from '../types/spot'
import type { Itinerary } from '../types/itinerary'
import type { Tour } from '../types/tour'
import type { ChurreProfile, Review } from '../types/churre'

// ─── SPOTS ──────────────────────────────────────────────
export const MOCK_SPOTS: Spot[] = [
  {
    id: 'spot-1',
    churreId: 'churre-1',
    name: 'Playa Yacila',
    description: 'La playa más auténtica y menos concurrida del norte. Aguas turquesas, arena dorada y un pueblo de pescadores que todavía vive del mar. Olvídate del turismo masivo.',
    localTip: 'Llega antes de las 10am para elegir tu spot y pide cebiche al pescador de la carpa azul — no tiene nombre ni letrero, pero es el mejor del litoral.',
    category: 'playa',
    photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
      'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80',
    ],
    lat: -5.0891,
    lng: -81.1023,
    address: 'Yacila, Paita, Piura',
    schedule: { 'Lun–Dom': 'Todo el día (libre)' },
    priceRange: 'free',
    status: 'verified',
    rating: 4.9,
    reviewCount: 87,
    tiktokUrls: [
      'https://www.tiktok.com/@elyinyan3/video/7597491501127552263?is_from_webapp=1&sender_device=pc',
      'https://www.tiktok.com/@anonimasafrodita_333/video/7600220747985931538',
    ],
    socialLinks: {
      instagram: '@yacila.piura',
      facebook: 'facebook.com/playayacila',
      whatsapp: '51987001122',
    },
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'spot-2',
    churreId: 'churre-3',
    name: 'Playa Colán',
    description: 'Una de las playas más largas del Perú con 12 km de arena blanca. Los casarones coloniales de madera sobre el agua son únicos en Sudamérica. Perfecto para relajarse.',
    localTip: 'El mirador del Cerro del Fraile al atardecer es magia pura. Sube 20 minutos y la vista te deja sin palabras. Los lugareños casi nunca llevan turistas ahí.',
    category: 'playa',
    photoUrl: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&q=80',
      'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800&q=80',
    ],
    lat: -5.0234,
    lng: -81.0512,
    address: 'Colán, Paita, Piura',
    schedule: { 'Lun–Dom': 'Todo el día (libre)' },
    priceRange: 'free',
    status: 'verified',
    rating: 4.7,
    reviewCount: 142,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@playa.colan',
      website: 'https://visitacolan.pe',
    },
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'spot-3',
    churreId: 'churre-1',
    name: 'Cebichería El Puerto · Paita',
    description: 'El mejor cebiche del norte chico, con materia prima directa del muelle de Paita. Su leche de tigre de cangrejo es legendaria entre los piuranos. Sin pretensiones, todo sabor.',
    localTip: 'Pide el cebiche mixto y la causa de atún. Llega antes de la 1pm o se quedan sin caballa fresca. Los martes el dueño trae cangrejo revienta.',
    category: 'gastronomia',
    photoUrl: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800&q=80',
      'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
      'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80',
    ],
    lat: -5.0831,
    lng: -81.1105,
    address: 'Muelle de Paita, Paita, Piura',
    schedule: {
      'Lun–Vie': '11:00 – 16:00',
      'Sáb–Dom': '10:00 – 15:00',
    },
    priceRange: 'low',
    status: 'verified',
    rating: 4.8,
    reviewCount: 213,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@cebicheriaelpuerto',
      facebook: 'facebook.com/elpuertopaita',
      whatsapp: '51976543210',
    },
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'spot-4',
    churreId: 'churre-1',
    name: 'Desayuno El Chalán',
    description: 'La mañana piurana comienza aquí. Tamalitos verdes con aguadito, café de Chulucanas y pan de horno de leña. La institución del desayuno en la ciudad desde 1978.',
    localTip: 'Pide la «mañanera» — no está en el menú, es la combinación que piden los locales: tamales + seco de cabrito + café. Solo hasta las 11am.',
    category: 'gastronomia',
    photoUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
    ],
    lat: -5.1945,
    lng: -80.6328,
    address: 'Jr. Libertad 342, Piura',
    schedule: {
      'Lun–Sáb': '06:30 – 12:00',
      'Dom': '07:00 – 11:00',
    },
    priceRange: 'low',
    status: 'verified',
    rating: 4.8,
    reviewCount: 398,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@elchalanpiura',
      facebook: 'elchalanpiura',
    },
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'spot-5',
    churreId: 'churre-2',
    name: 'Mercado Artesanal de Catacaos',
    description: 'El corazón artesanal del norte peruano. Filigrana de oro y plata, cerámicas, paja toquilla y los mejores picarones de la región. Un mundo en sí mismo.',
    localTip: 'Negocia con cariño — los precios iniciales son para turistas. Pregunta por doña Rosa en el puesto 34 para joyería fina, ella vende a precio justo.',
    category: 'mercados',
    photoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    lat: -5.2634,
    lng: -80.6741,
    address: 'Catacaos, Piura',
    schedule: { 'Lun–Dom': '08:00 – 17:00' },
    priceRange: 'low',
    status: 'verified',
    rating: 4.6,
    reviewCount: 521,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@artesaniacatacaos',
      facebook: 'mercadocatacaos',
      whatsapp: '51956781234',
    },
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'spot-6',
    churreId: 'churre-2',
    name: 'Museo Vicus · Centro de Piura',
    description: 'La cultura Vicús fue una de las más sofisticadas del antiguo Perú y casi nadie la conoce. Cerámica, orfebrería y textiles de 2,000 años de antigüedad. Entrada libre.',
    localTip: 'El arqueólogo Manuel da tours gratuitos los jueves a las 10am si vas y le preguntas amablemente. No lo anuncian en ningún lado.',
    category: 'cultura',
    photoUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80',
      'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=80',
    ],
    lat: -5.1945,
    lng: -80.6295,
    address: 'Jr. Huánuco 894, Piura',
    schedule: {
      'Mar–Sáb': '09:00 – 17:00',
      'Dom': '09:00 – 13:00',
      'Lun': 'Cerrado',
    },
    priceRange: 'free',
    status: 'verified',
    rating: 4.5,
    reviewCount: 89,
    tiktokUrls: [],
    socialLinks: {
      website: 'https://museovicus.gob.pe',
      facebook: 'museovicuspiura',
    },
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'spot-7',
    churreId: 'churre-2',
    name: 'Casa Grau · Centro Histórico',
    description: 'La casa natal del Almirante Miguel Grau, el héroe de Iquique. Arquitectura colonial perfectamente preservada con jardines, museo y una vista íntima de la historia piurana.',
    localTip: 'La señora Lucía teje en el patio interior cada mañana y te cuenta historias de la familia Grau que no aparecen en ningún libro. Solo pregúntale.',
    category: 'cultura',
    photoUrl: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=80',
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    ],
    lat: -5.1937,
    lng: -80.6312,
    address: 'Jr. Tacna 662, Piura',
    schedule: {
      'Mar–Dom': '09:00 – 17:00',
      'Lun': 'Cerrado',
    },
    priceRange: 'low',
    status: 'verified',
    rating: 4.4,
    reviewCount: 167,
    tiktokUrls: [],
    socialLinks: {
      facebook: 'casagraupiura',
    },
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'spot-8',
    churreId: 'churre-2',
    name: 'Mirador de Canchaque',
    description: 'A 1,200 msnm entre cafetales y bosques de neblina. El mirador te regala una vista de 180° del valle del Huancabamba. Aire puro, silencio absoluto y café de altura recién cosechado.',
    localTip: 'Don Ernesto en la finca «La Esperanza» te deja ver el proceso de beneficio del café si llegas antes de las 8am. Prueba el café en taza caliente ahí mismo.',
    category: 'sierra',
    photoUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    ],
    lat: -5.3812,
    lng: -79.5631,
    address: 'Canchaque, Huancabamba, Piura',
    schedule: { 'Lun–Dom': 'Todo el día (libre)' },
    priceRange: 'free',
    status: 'verified',
    rating: 4.8,
    reviewCount: 43,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@canchaque.piura',
      whatsapp: '51943210987',
    },
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'spot-9',
    churreId: 'churre-2',
    name: 'Lagunas de Las Huaringas',
    description: 'Las lagunas sagradas a 3,900 msnm donde los curanderos andinos realizan rituales de sanación desde tiempos preincaicos. Mística, poder y naturaleza en estado puro.',
    localTip: 'El maestro curandero don Aurelio hace la limpia ritual al amanecer solo si lo contactas con 3 días de anticipación. Lleva ofrendas: pétalos de flores y chocllo.',
    category: 'sierra',
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    ],
    lat: -5.1672,
    lng: -79.4123,
    address: 'Huancabamba, Piura',
    schedule: { 'Lun–Dom': 'Todo el día (coordinar con guía)' },
    priceRange: 'mid',
    status: 'verified',
    rating: 4.9,
    reviewCount: 58,
    tiktokUrls: [],
    socialLinks: {},
    createdAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'spot-10',
    churreId: 'churre-2',
    name: 'Santuario de Ayabaca',
    description: 'El señor cautivo de Ayabaca convoca a miles de peregrinos cada año. La ciudad colonial a 2,715 msnm ofrece artesanía única, paisaje andino y una espiritualidad palpable.',
    localTip: 'La feria del 13 de octubre es la más grande de la sierra piurana — tres días de música, artesanía y gastronomía serrana. Reserva alojamiento con meses de anticipación.',
    category: 'sierra',
    photoUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
      'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80',
    ],
    lat: -4.6382,
    lng: -79.7181,
    address: 'Ayabaca, Piura',
    schedule: { 'Lun–Dom': '06:00 – 19:00' },
    priceRange: 'free',
    status: 'verified',
    rating: 4.7,
    reviewCount: 231,
    tiktokUrls: [],
    socialLinks: {
      facebook: 'santuarioayabaca',
      website: 'https://ayabaca.pe',
    },
    createdAt: '2024-04-10T10:00:00Z',
  },
  {
    id: 'spot-11',
    churreId: 'churre-1',
    name: 'Jipibar · Piura Centro',
    description: 'El bar cultural de Piura. Live music los jueves, exposiciones de artistas piuranos, coctelería con frutos del norte y la energía de la escena creativa local. No te lo pierdes.',
    localTip: 'La «chicha sour» con chicha de jora de Catacaos es la copa estrella, pero no está en la carta escrita. Pídesela al bartender Javier y listo.',
    category: 'relax',
    photoUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
      'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80',
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
    ],
    lat: -5.1948,
    lng: -80.6341,
    address: 'Av. Grau 215, Piura',
    schedule: {
      'Mié–Jue': '18:00 – 01:00',
      'Vie–Sáb': '17:00 – 02:00',
      'Dom': '16:00 – 23:00',
    },
    priceRange: 'mid',
    status: 'verified',
    rating: 4.6,
    reviewCount: 114,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@jipibar.piura',
      tiktok: '@jipibar',
      facebook: 'jipibarpiura',
      whatsapp: '51965432109',
    },
    createdAt: '2024-04-15T10:00:00Z',
  },
  {
    id: 'spot-12',
    churreId: 'churre-3',
    name: 'Sunset desde La Islilla',
    description: 'El atardecer más épico del litoral piurano. Un pueblito de pescadores donde el sol cae directo sobre el Pacífico pintando el cielo de naranja y magenta. No hay palabras.',
    localTip: 'Los domingos hay música en vivo en la playa central — guitarras y cajón. Llega a las 5:30pm para el mejor ángulo fotográfico desde el muelle de madera.',
    category: 'playa',
    photoUrl: 'https://images.unsplash.com/photo-1506197061074-a3933a5b60db?w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1506197061074-a3933a5b60db?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    lat: -5.1523,
    lng: -81.2341,
    address: 'La Islilla, Paita, Piura',
    schedule: { 'Lun–Dom': 'Todo el día (atardecer ~18:00)' },
    priceRange: 'free',
    status: 'verified',
    rating: 4.9,
    reviewCount: 76,
    tiktokUrls: [],
    socialLinks: {
      instagram: '@islilla.piura',
    },
    createdAt: '2024-04-20T10:00:00Z',
  },
]
// ─── CHURRES ─────────────────────────────────────────────
export const MOCK_CHURRES: ChurreProfile[] = [
  {
    id: 'churre-1',
    userId: 'user-c1',
    name: 'Carlos Ríos',
    bio: 'Piurano de ley. Sé cada rincón de la costa desde Colán hasta Sechura. 45 tours, cero turistas aburridos. Te muestro el Piura real, no el del folleto.',
    avatarUrl: '',
    avatarColor: '#FF5500',
    university: 'UDEP',
    zones: ['Piura', 'Catacaos', 'Paita', 'Colán', 'Yacila'],
    specialties: ['playa', 'gastronomia'],
    rating: 4.9,
    toursCount: 45,
    isVerified: true,
  },
  {
    id: 'churre-2',
    userId: 'user-c2',
    name: 'Ana Flores',
    bio: 'Estudiante de arqueología en la UNP. Mi corazón está en la sierra piurana — Canchaque, Ayabaca, Huancabamba. Te llevo donde la modernidad no ha llegado.',
    avatarUrl: '',
    avatarColor: '#7209b7',
    university: 'UNP',
    zones: ['Piura', 'Canchaque', 'Ayabaca', 'Huancabamba'],
    specialties: ['sierra', 'cultura'],
    rating: 4.8,
    toursCount: 32,
    isVerified: true,
  },
  {
    id: 'churre-3',
    userId: 'user-c3',
    name: 'Miguel Távara',
    bio: 'Surfista, fotógrafo y guía de aventura. Lobitos, Talara, La Islilla — manejo cada ola y cada mirador. Para los que quieren adrenalina con vista al Pacífico.',
    avatarUrl: '',
    avatarColor: '#0077b6',
    university: 'UCV',
    zones: ['Piura', 'Lobitos', 'Talara', 'La Islilla'],
    specialties: ['playa', 'aventura'],
    rating: 4.7,
    toursCount: 28,
    isVerified: true,
  },
]

// ─── TOURS ────────────────────────────────────────────────
export const MOCK_TOURS: Tour[] = [
  {
    id: 'tour-1',
    churreId: 'churre-1',
    touristId: 'tourist-1',
    touristName: 'Valentina Cruz',
    touristAvatar: 'VC',
    type: 'full_day',
    date: '2026-04-14',
    time: '07:00',
    price: 120,
    status: 'confirmed',
    notes: 'Alérgica al mariscos. Prefiere playas tranquilas.',
    zones: ['Yacila', 'Paita'],
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'tour-2',
    churreId: 'churre-1',
    touristId: 'tourist-2',
    touristName: 'Diego Morales',
    touristAvatar: 'DM',
    type: 'half_day',
    date: '2026-04-15',
    time: '09:00',
    price: 80,
    status: 'pending',
    notes: 'Quiere probar la gastronomía local y el mercado de Catacaos.',
    zones: ['Piura', 'Catacaos'],
    createdAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 'tour-3',
    churreId: 'churre-1',
    touristId: 'tourist-3',
    touristName: 'Sofía Ramírez',
    touristAvatar: 'SR',
    type: 'full_day',
    date: '2026-04-16',
    time: '07:30',
    price: 140,
    status: 'pending',
    notes: 'Viaja con su pareja. Primera vez en Piura.',
    zones: ['Colán', 'Yacila', 'Paita'],
    createdAt: '2026-04-11T14:00:00Z',
  },
  {
    id: 'tour-4',
    churreId: 'churre-1',
    touristId: 'tourist-4',
    touristName: 'Andrés Vega',
    touristAvatar: 'AV',
    type: 'half_day',
    date: '2026-04-08',
    time: '10:00',
    price: 80,
    status: 'completed',
    notes: 'Le encantó el cebiche de El Puerto.',
    zones: ['Paita', 'Yacila'],
    createdAt: '2026-04-06T09:00:00Z',
  },
  {
    id: 'tour-5',
    churreId: 'churre-1',
    touristId: 'tourist-5',
    touristName: 'Lucía Mendoza',
    touristAvatar: 'LM',
    type: 'full_day',
    date: '2026-04-05',
    time: '08:00',
    price: 120,
    status: 'completed',
    notes: '',
    zones: ['Piura', 'Catacaos', 'Colán'],
    createdAt: '2026-04-02T11:00:00Z',
  },
  {
    id: 'tour-6',
    churreId: 'churre-1',
    touristId: 'tourist-6',
    touristName: 'Roberto Lara',
    touristAvatar: 'RL',
    type: 'half_day',
    date: '2026-04-03',
    time: '09:00',
    price: 80,
    status: 'cancelled',
    notes: 'Canceló por lluvia imprevista.',
    zones: ['Piura'],
    createdAt: '2026-04-01T15:00:00Z',
  },
  {
    id: 'tour-7',
    churreId: 'churre-1',
    touristId: 'tourist-7',
    touristName: 'Carmen Díaz',
    touristAvatar: 'CD',
    type: 'full_day',
    date: '2026-04-18',
    time: '07:00',
    price: 130,
    status: 'confirmed',
    notes: 'Fotógrafa profesional. Quiere los mejores atardeceres.',
    zones: ['La Islilla', 'Paita'],
    createdAt: '2026-04-10T16:00:00Z',
  },
  {
    id: 'tour-8',
    churreId: 'churre-1',
    touristId: 'tourist-8',
    touristName: 'Pablo Torres',
    touristAvatar: 'PT',
    type: 'half_day',
    date: '2026-04-20',
    time: '10:00',
    price: 80,
    status: 'pending',
    notes: 'Familia con 2 niños. Busca actividades tranquilas.',
    zones: ['Catacaos', 'Piura'],
    createdAt: '2026-04-11T09:00:00Z',
  },
]

// ─── REVIEWS ──────────────────────────────────────────────
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    churreId: 'churre-1',
    touristId: 'tourist-4',
    touristName: 'Andrés Vega',
    touristAvatar: 'AV',
    rating: 5,
    comment: 'Carlos es increíble. No solo conoce cada rincón de Piura, sino que te hace sentir parte del lugar. El cebiche de El Puerto fue una revelación. 100% recomendado.',
    tourType: 'Medio día · Paita y Yacila',
    createdAt: '2026-04-09T10:00:00Z',
  },
  {
    id: 'rev-2',
    churreId: 'churre-1',
    touristId: 'tourist-5',
    touristName: 'Lucía Mendoza',
    touristAvatar: 'LM',
    rating: 5,
    comment: 'Vine a Piura sin expectativas y salí enamorada de la ciudad. Carlos sabe cómo mostrarte lo auténtico sin filtros. Los tamalitos del Chalán al amanecer son para llorar de felicidad.',
    tourType: 'Día completo · Piura, Catacaos y Colán',
    createdAt: '2026-04-07T14:00:00Z',
  },
  {
    id: 'rev-3',
    churreId: 'churre-1',
    touristId: 'tourist-9',
    touristName: 'María Gutiérrez',
    touristAvatar: 'MG',
    rating: 5,
    comment: 'La experiencia más auténtica que he tenido viajando por el Perú. Carlos nos llevó a lugares que no existen en TripAdvisor ni en ninguna guía. Eso es lo que busco cuando viajo.',
    tourType: 'Día completo · Costa norte',
    createdAt: '2026-03-28T11:00:00Z',
  },
  {
    id: 'rev-4',
    churreId: 'churre-1',
    touristId: 'tourist-10',
    touristName: 'Fernando Soto',
    touristAvatar: 'FS',
    rating: 5,
    comment: 'Puntual, divertido, conocedor y honesto. Carlos te dice la verdad sobre los precios, las distancias y los lugares. Exactamente lo que necesitas en un guía local.',
    tourType: 'Medio día · Playas de Paita',
    createdAt: '2026-03-20T09:00:00Z',
  },
  {
    id: 'rev-5',
    churreId: 'churre-1',
    touristId: 'tourist-11',
    touristName: 'Isabela Costa',
    touristAvatar: 'IC',
    rating: 4,
    comment: 'Muy buena experiencia. Carlos conoce muy bien la zona y es súper amable. Solo le doy 4 estrellas porque el primer spot tardó un poco en abrir.',
    tourType: 'Día completo · Catacaos y playas',
    createdAt: '2026-03-10T16:00:00Z',
  },
  {
    id: 'rev-6',
    churreId: 'churre-1',
    touristId: 'tourist-12',
    touristName: 'Jorge Espinoza',
    touristAvatar: 'JE',
    rating: 5,
    comment: 'Carlos no guía, CONDUCE experiencias. Cada parada tiene una historia, un local que conoce de toda la vida, un sabor que no encuentras en otro lugar. Piura es increíble gracias a él.',
    tourType: 'Fin de semana · Tour completo norte',
    createdAt: '2026-02-28T12:00:00Z',
  },
]

// ─── DEFAULT ITINERARY (demo) ──────────────────────────────
export const MOCK_ITINERARY: Itinerary = {
  id: 'itinerary-demo',
  userId: 'tourist-demo',
  title: 'Playa + Ceviche',
  status: 'in_progress',
  preferences: {
    interests: ['playa', 'gastronomia'],
    time: 'full',
    group: 'couple',
    budget: 'mid',
  },
  stops: [
    {
      id: 'stop-1',
      spotId: 'spot-4',
      spotName: 'Desayuno El Chalán',
      time: '07:00',
      description: 'Tamalitos verdes con café de Chulucanas. El inicio perfecto de un día piurano.',
      localTip: 'Pide la «mañanera» — no está en el menú. Solo hasta las 11am.',
      travelToNext: '→ 40 min en auto hasta Paita',
      photoUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
      lat: -5.1945,
      lng: -80.6328,
      visited: false,
    },
    {
      id: 'stop-2',
      spotId: 'spot-1',
      spotName: 'Playa Yacila',
      time: '09:30',
      description: 'La menos concurrida del norte. Aguas tranquilas y arena dorada.',
      localTip: 'Antes de las 10am para elegir el mejor spot.',
      travelToNext: '→ 15 min en moto-taxi',
      photoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      lat: -5.0891,
      lng: -81.1023,
      visited: false,
    },
    {
      id: 'stop-3',
      spotId: 'spot-3',
      spotName: 'Cebichería El Puerto · Paita',
      time: '13:00',
      description: 'Leche de tigre de cangrejo y cebiche mixto. La joya del litoral.',
      localTip: 'Pide el cebiche mixto, llega antes de la 1pm o se acaba.',
      travelToNext: '→ 25 min en auto',
      photoUrl: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800&q=80',
      lat: -5.0831,
      lng: -81.1105,
      visited: false,
    },
    {
      id: 'stop-4',
      spotId: 'spot-12',
      spotName: 'Sunset desde La Islilla',
      time: '17:30',
      description: 'El sol cae directo sobre el Pacífico. Los domingos hay música en vivo.',
      localTip: 'Llega a las 5:30pm para el mejor ángulo fotográfico.',
      travelToNext: '→ Fin del día',
      photoUrl: 'https://images.unsplash.com/photo-1506197061074-a3933a5b60db?w=800&q=80',
      lat: -5.1523,
      lng: -81.2341,
      visited: false,
    },
  ],
  generatedBy: 'manual',
  isSaved: false,
  createdAt: new Date().toISOString(),
}

// ─── WEATHER MOCK ─────────────────────────────────────────
export const MOCK_WEATHER = {
  temp: 28,
  condition: 'Soleado',
  emoji: '☀️',
  humidity: 72,
  windSpeed: 15,
  tip: 'Perfecto para playa hoy',
}
